# PERKENALAN

In [ ]:
'''
=================================================

Graded Challenge 2

Nama  : Ahmad Qais Alfiansyah
Batch : RMT-026

Saya berencana untuk menjadi dropshiper,
saya akan ambil produk Seblak yang sedang viral saat ini.

Berdasarkan ilmu yang saya pelajari di Hacktiv8, saya akan
memulai dengan melakukan Web Scraping di salah satu website
e-commerce terbesar di Indonesia, yaitu Tokopedia.

Dari data hasil scraping itu, saya berharap mendapatkan insight
yang dapat membantu saya mengambil berbagai keputusan.

Saya akan menggunakan OKR Framework untuk project dropsihp ini dimana:

Objective:
Mendapatkan penghasilan tambahan sebesar 30juta dengan menjadi dropshiper dalam waktu 6 bulan

Key Result:
1. Mengumpulkan 50 - 100 data penjualan di Tokopedia
2. Tidak memperhitungkan data dari produk yang diiklankan
3. Menghitung potensi pemasukan, jika lebih atau sama dengan kebutuhan saya, maka
project ini dilanjutkan
4. Mencari insight daerah mana yang menjual produk lebih murah
5. Mencari tahu apakah semakin murah harga, semakin banyak pembeli?

=================================================
'''

'\n=================================================\n\nGraded Challenge 2\n\nNama  : Ahmad Qais Alfiansyah\nBatch : RMT-026\n\nSaya berencana untuk menjadi dropshiper,\nsaya akan ambil produk Seblak yang sedang viral saat ini.\n\nBerdasarkan ilmu yang saya pelajari di Hacktiv8, saya akan\nmemulai dengan melakukan Web Scraping di salah satu website\ne-commerce terbesar di Indonesia, yaitu Tokopedia.\n\nDari data hasil scraping itu, saya berharap mendapatkan insight\nyang dapat membantu saya mengambil berbagai keputusan.\n\nSaya akan menggunakan OKR Framework untuk project dropsihp ini dimana:\n\nObjective:\nMendapatkan penghasilan tambahan sebesar 30juta dengan menjadi dropshiper dalam waktu 6 bulan\n\nKey Result:\n1. Mengumpulkan 50 - 100 data penjualan di Tokopedia\n2. Tidak memperhitungkan data dari produk yang diiklankan\n3. Menghitung potensi pemasukan, jika lebih atau sama dengan kebutuhan saya, maka\nproject ini dilanjutkan\n4. Mencari insight daerah mana yang menjual produk lebih murah\n5. Mencari tahu apakah semakin murah harga, semakin banyak pembeli?\n\n=================================================\n'

# PROBLEM STATEMENT

Saya memiliki impian beribadah ke tanah suci tahun depan. Saya harus mendapatkan penghasilan tambahan setidaknya 30juta Rupiah dalam waktu 6 bulan. Saya akan berjualan seblak yang sedang viral saati ini. Saya akan memulainya dengan mencari list supplier dan memilih supplier yang terpercaya, dan murah untuk mencapai hal itu, pertama saya akan melakukan web scraping di website Tokopedia.

# WEB SCRAPING

In [110]:
# setup via requests, import BS dan PD
import requests
from bs4 import BeautifulSoup
import pandas as pd
from scipy import stats
from scipy.stats import norm
import numpy as np

In [111]:
# Fungsi untuk melakukan scraping pada satu halaman pencarian
def scrape_page(url):
    headers = {'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36 OPR/58.0.3135.79'}
    response = requests.get(url, headers=headers)

    soup = BeautifulSoup(response.text, 'html.parser')

    products = []

    product_elements = soup.find_all('div', class_='css-llwpbs') # <-- css-llwpbs adalah class produk reguler
    i = 1


    '''
    Setelah mencoba dan mencoba, saya membatasi pencarian 10 produk saja per page
    Hal ini supaya tidaj terlalu banyak nilai kosong
    tetapi pada selanjutnya fungsi tetap dilooping sampai ke page 10
    mendapatkan 90 entries data
    pada tahap ini saya juga berusaha mendapatkan:
    Nama Produk, Harga Produk, Penjual, Kota Toko, Banyaknya Terjual, dan Rating Produk.
    '''
    
    for product in product_elements:
        if i == 10:
            break

        try:
            name = product.find('div', class_='css-3um8ox').text.strip()
            print(name)
        except:
            name = None

        try:
            price = product.find('div', class_='css-h66vau').text.strip()
            print(price)
        except:
            price = None
        
        seller_element = product.find('div', class_='css-1rn0irl')
        try:
            seller = seller_element.find('span', class_='prd_link-shop-name').text.strip()
            print(seller)
        except:
            seller = None

        try:
            city = seller_element.find('span', class_='prd_link-shop-loc').text.strip()
            print(seller)
        except:
            city = None


        rating_sold_element = product.find('div', class_='css-26zmlj')
        try:
            sold = rating_sold_element.find('span', class_='css-1sgek4h').text.strip() if rating_sold_element else None
            print(sold)
        except:
            sold = None

        try:
            rating = rating_sold_element.find('span', class_='css-t70v7i').text.strip() if rating_sold_element else None
            print(rating)
        except:
            rating = None

        products.append({
            'Nama Produk': name,
            'Harga Produk': price,
            'Nama Toko' : seller,
            'Kota Toko': city,
            'Banyaknya Terjual': sold,
            'Rating Produk': rating
        })

        i+=1

    return products

In [112]:
# Pada tahap ini proses looping sampai 10 page dilakukan
def scrape_multiple_pages(base_url, num_pages):
    all_products = []

    for page in range(1, num_pages + 1):
        url = f'{base_url}&page={page}'
        products = scrape_page(url)
        all_products.extend(products)

    return all_products

# URL Tokopedia pencarian "seblak"
base_url = 'https://www.tokopedia.com/search?navsource=&page=1&q=seblak&srp_component_id=02.01.00.00&srp_page_id=&srp_page_title=&st='
num_pages = 10  # Jumlah halaman yang ingin di-scrape

# Lakukan scraping
data = scrape_multiple_pages(base_url, num_pages)

Gelifood Seblak Instan Kerupuk Mawar Bumbu Kencur Rafael Pedas Gurih
Rp13.000
Lidigeli
Lidigeli
250+ terjual
4.9
Seblak Instan Ceu Nthien Khas Bandung Rasana Ngeunah Pisan
Rp15.000
Central Seblak Nusantara
Central Seblak Nusantara
2rb+ terjual
4.9
Seblak Rafael, Seblak Coet Instan Halal
Rp25.000
Brother Meat Shop
Brother Meat Shop
50+ terjual
5.0
Seblak Instan
Rp8.000
ROEMAH MOSLEM
ROEMAH MOSLEM
19 terjual
5.0
KRUPUK STIK RASA UDANG CAP PADI KAPAS KHAS INDRAMAYU BISA BUAT SEBLAK
Rp19.050
dariimyu
dariimyu
100+ terjual
5.0
Seblak Instan Pedas Home Made
Rp3.500
the Dhecip
the Dhecip
2rb+ terjual
4.8
Kylafood Seblak Cup
Rp11.000
Kylafood Jakarta
Kylafood Jakarta
100+ terjual
4.9
seblak frozen
Rp10.400
pelangi girls naget
pelangi girls naget
2rb+ terjual
4.9
Seblak RAFAEL | Seblak MAMANG RAFAEL | Seblak Viral
Rp40.000
Naturally Plus Jakarta
Naturally Plus Jakarta
100+ terjual
5.0
Gelifood Seblak Instan Kerupuk Mawar Bumbu Kencur Rafael Pedas Gurih
Rp13.000
Lidigeli
Lidigeli
250+ terjual
4.9
Seblak Instan Ceu Nthien Khas Bandung Rasana Ngeunah Pisan
Rp15.000
Central Seblak Nusantara
Central Seblak Nusantara
2rb+ terjual
4.9
Seblak Rafael, Seblak Coet Instan Halal
Rp25.000
Brother Meat Shop
Brother Meat Shop
50+ terjual
5.0
Seblak Instan
Rp8.000
ROEMAH MOSLEM
ROEMAH MOSLEM
19 terjual
5.0
KRUPUK STIK RASA UDANG CAP PADI KAPAS KHAS INDRAMAYU BISA BUAT SEBLAK
Rp19.050
dariimyu
dariimyu
100+ terjual
5.0
Seblak Instan Pedas Home Made
Rp3.500
the Dhecip
the Dhecip
2rb+ terjual
4.8
Kylafood Seblak Cup
Rp11.000
Kylafood Jakarta
Kylafood Jakarta
100+ terjual
4.9
seblak frozen
Rp10.400
pelangi girls naget
pelangi girls naget
2rb+ terjual
4.9
Seblak RAFAEL | Seblak MAMANG RAFAEL | Seblak Viral
Rp40.000
Naturally Plus Jakarta
Naturally Plus Jakarta
100+ terjual
5.0
Gelifood Seblak Instan Kerupuk Mawar Bumbu Kencur Rafael Pedas Gurih
Rp13.000
Lidigeli
Lidigeli
250+ terjual
4.9
Seblak Instan Ceu Nthien Khas Bandung Rasana Ngeunah Pisan
Rp15.000
Central Seblak Nusantara
Central Seblak Nusantara
2rb+ terjual
4.9
Seblak Rafael, Seblak Coet Instan Halal
Rp25.000
Brother Meat Shop
Brother Meat Shop
50+ terjual
5.0
Seblak Instan
Rp8.000
ROEMAH MOSLEM
ROEMAH MOSLEM
19 terjual
5.0
KRUPUK STIK RASA UDANG CAP PADI KAPAS KHAS INDRAMAYU BISA BUAT SEBLAK
Rp19.050
dariimyu
dariimyu
100+ terjual
5.0
Seblak Instan Pedas Home Made
Rp3.500
the Dhecip
the Dhecip
2rb+ terjual
4.8
Kylafood Seblak Cup
Rp11.000
Kylafood Jakarta
Kylafood Jakarta
100+ terjual
4.9
seblak frozen
Rp10.400
pelangi girls naget
pelangi girls naget
2rb+ terjual
4.9
Seblak RAFAEL | Seblak MAMANG RAFAEL | Seblak Viral
Rp40.000
Naturally Plus Jakarta
Naturally Plus Jakarta
100+ terjual
5.0
Gelifood Seblak Instan Kerupuk Mawar Bumbu Kencur Rafael Pedas Gurih
Rp13.000
Lidigeli
Lidigeli
250+ terjual
4.9
Seblak Instan Ceu Nthien Khas Bandung Rasana Ngeunah Pisan
Rp15.000
Central Seblak Nusantara
Central Seblak Nusantara
2rb+ terjual
4.9
Seblak Rafael, Seblak Coet Instan Halal
Rp25.000
Brother Meat Shop
Brother Meat Shop
50+ terjual
5.0
Seblak Instan
Rp8.000
ROEMAH MOSLEM
ROEMAH MOSLEM
19 terjual
5.0
KRUPUK STIK RASA UDANG CAP PADI KAPAS KHAS INDRAMAYU BISA BUAT SEBLAK
Rp19.050
dariimyu
dariimyu
100+ terjual
5.0
Seblak Instan Pedas Home Made
Rp3.500
the Dhecip
the Dhecip
2rb+ terjual
4.8
Kylafood Seblak Cup
Rp11.000
Kylafood Jakarta
Kylafood Jakarta
100+ terjual
4.9
seblak frozen
Rp10.400
pelangi girls naget
pelangi girls naget
2rb+ terjual
4.9
Seblak RAFAEL | Seblak MAMANG RAFAEL | Seblak Viral
Rp40.000
Naturally Plus Jakarta
Naturally Plus Jakarta
100+ terjual
5.0
Gelifood Seblak Instan Kerupuk Mawar Bumbu Kencur Rafael Pedas Gurih
Rp13.000
Lidigeli
Lidigeli
250+ terjual
4.9
Seblak Instan Ceu Nthien Khas Bandung Rasana Ngeunah Pisan
Rp15.000
Central Seblak Nusantara
Central Seblak Nusantara
2rb+ terjual
4.9
Seblak Rafael, Seblak Coet Instan Halal
Rp25.000
Brother Meat Shop
Brother Meat Shop
50+ terjual
5.0
Seblak Instan
Rp8.000
ROEMAH MOSLEM
ROEMAH MOSLEM
19 terjual
5.0
KRUPUK STIK RASA UDANG CAP PADI KAPAS KHAS INDRAMAYU BISA BUAT SEBLAK
Rp19.050
dariimyu
dariimyu
100+ terjual
5.0
Seblak Instan Pedas Home Made
Rp3.500
the Dhecip
the Dhecip
2rb+ terjual
4.8
Kylafood Seblak Cup
Rp11.000
Kylafood Jakarta
Kylafood Jakarta
100+ terjual
4.9
seblak frozen
Rp10.400
pelangi girls naget
pelangi girls naget
2rb+ terjual
4.9
Seblak RAFAEL | Seblak MAMANG RAFAEL | Seblak Viral
Rp40.000
Naturally Plus Jakarta
Naturally Plus Jakarta
100+ terjual
5.0
Gelifood Seblak Instan Kerupuk Mawar Bumbu Kencur Rafael Pedas Gurih
Rp13.000
Lidigeli
Lidigeli
250+ terjual
4.9
Seblak Instan Ceu Nthien Khas Bandung Rasana Ngeunah Pisan
Rp15.000
Central Seblak Nusantara
Central Seblak Nusantara
2rb+ terjual
4.9
Seblak Rafael, Seblak Coet Instan Halal
Rp25.000
Brother Meat Shop
Brother Meat Shop
50+ terjual
5.0
Seblak Instan
Rp8.000
ROEMAH MOSLEM
ROEMAH MOSLEM
19 terjual
5.0
KRUPUK STIK RASA UDANG CAP PADI KAPAS KHAS INDRAMAYU BISA BUAT SEBLAK
Rp19.050
dariimyu
dariimyu
100+ terjual
5.0
Seblak Instan Pedas Home Made
Rp3.500
the Dhecip
the Dhecip
2rb+ terjual
4.8
Kylafood Seblak Cup
Rp11.000
Kylafood Jakarta
Kylafood Jakarta
100+ terjual
4.9
seblak frozen
Rp10.400
pelangi girls naget
pelangi girls naget
2rb+ terjual
4.9
Seblak RAFAEL | Seblak MAMANG RAFAEL | Seblak Viral
Rp40.000
Naturally Plus Jakarta
Naturally Plus Jakarta
100+ terjual
5.0
Gelifood Seblak Instan Kerupuk Mawar Bumbu Kencur Rafael Pedas Gurih
Rp13.000
Lidigeli
Lidigeli
250+ terjual
4.9
Seblak Instan Ceu Nthien Khas Bandung Rasana Ngeunah Pisan
Rp15.000
Central Seblak Nusantara
Central Seblak Nusantara
2rb+ terjual
4.9
Seblak Rafael, Seblak Coet Instan Halal
Rp25.000
Brother Meat Shop
Brother Meat Shop
50+ terjual
5.0
Seblak Instan
Rp8.000
ROEMAH MOSLEM
ROEMAH MOSLEM
19 terjual
5.0
KRUPUK STIK RASA UDANG CAP PADI KAPAS KHAS INDRAMAYU BISA BUAT SEBLAK
Rp19.050
dariimyu
dariimyu
100+ terjual
5.0
Seblak Instan Pedas Home Made
Rp3.500
the Dhecip
the Dhecip
2rb+ terjual
4.8
Kylafood Seblak Cup
Rp11.000
Kylafood Jakarta
Kylafood Jakarta
100+ terjual
4.9
seblak frozen
Rp10.400
pelangi girls naget
pelangi girls naget
2rb+ terjual
4.9
Seblak RAFAEL | Seblak MAMANG RAFAEL | Seblak Viral
Rp40.000
Naturally Plus Jakarta
Naturally Plus Jakarta
100+ terjual
5.0
Gelifood Seblak Instan Kerupuk Mawar Bumbu Kencur Rafael Pedas Gurih
Rp13.000
Lidigeli
Lidigeli
250+ terjual
4.9
Seblak Instan Ceu Nthien Khas Bandung Rasana Ngeunah Pisan
Rp15.000
Central Seblak Nusantara
Central Seblak Nusantara
2rb+ terjual
4.9
Seblak Rafael, Seblak Coet Instan Halal
Rp25.000
Brother Meat Shop
Brother Meat Shop
50+ terjual
5.0
Seblak Instan
Rp8.000
ROEMAH MOSLEM
ROEMAH MOSLEM
19 terjual
5.0
KRUPUK STIK RASA UDANG CAP PADI KAPAS KHAS INDRAMAYU BISA BUAT SEBLAK
Rp19.050
dariimyu
dariimyu
100+ terjual
5.0
Seblak Instan Pedas Home Made
Rp3.500
the Dhecip
the Dhecip
2rb+ terjual
4.8
Kylafood Seblak Cup
Rp11.000
Kylafood Jakarta
Kylafood Jakarta
100+ terjual
4.9
seblak frozen
Rp10.400
pelangi girls naget
pelangi girls naget
2rb+ terjual
4.9
Seblak RAFAEL | Seblak MAMANG RAFAEL | Seblak Viral
Rp40.000
Naturally Plus Jakarta
Naturally Plus Jakarta
100+ terjual
5.0
Gelifood Seblak Instan Kerupuk Mawar Bumbu Kencur Rafael Pedas Gurih
Rp13.000
Lidigeli
Lidigeli
250+ terjual
4.9
Seblak Instan Ceu Nthien Khas Bandung Rasana Ngeunah Pisan
Rp15.000
Central Seblak Nusantara
Central Seblak Nusantara
2rb+ terjual
4.9
Seblak Rafael, Seblak Coet Instan Halal
Rp25.000
Brother Meat Shop
Brother Meat Shop
50+ terjual
5.0
Seblak Instan
Rp8.000
ROEMAH MOSLEM
ROEMAH MOSLEM
19 terjual
5.0
KRUPUK STIK RASA UDANG CAP PADI KAPAS KHAS INDRAMAYU BISA BUAT SEBLAK
Rp19.050
dariimyu
dariimyu
100+ terjual
5.0
Seblak Instan Pedas Home Made
Rp3.500
the Dhecip
the Dhecip
2rb+ terjual
4.8
Kylafood Seblak Cup
Rp11.000
Kylafood Jakarta
Kylafood Jakarta
100+ terjual
4.9
seblak frozen
Rp10.400
pelangi girls naget
pelangi girls naget
2rb+ terjual
4.9
Seblak RAFAEL | Seblak MAMANG RAFAEL | Seblak Viral
Rp40.000
Naturally Plus Jakarta
Naturally Plus Jakarta
100+ terjual
5.0
Gelifood Seblak Instan Kerupuk Mawar Bumbu Kencur Rafael Pedas Gurih
Rp13.000
Lidigeli
Lidigeli
250+ terjual
4.9
Seblak Instan Ceu Nthien Khas Bandung Rasana Ngeunah Pisan
Rp15.000
Central Seblak Nusantara
Central Seblak Nusantara
2rb+ terjual
4.9
Seblak Rafael, Seblak Coet Instan Halal
Rp25.000
Brother Meat Shop
Brother Meat Shop
50+ terjual
5.0
Seblak Instan
Rp8.000
ROEMAH MOSLEM
ROEMAH MOSLEM
19 terjual
5.0
KRUPUK STIK RASA UDANG CAP PADI KAPAS KHAS INDRAMAYU BISA BUAT SEBLAK
Rp19.050
dariimyu
dariimyu
100+ terjual
5.0
Seblak Instan Pedas Home Made
Rp3.500
the Dhecip
the Dhecip
2rb+ terjual
4.8
Kylafood Seblak Cup
Rp11.000
Kylafood Jakarta
Kylafood Jakarta
100+ terjual
4.9
seblak frozen
Rp10.400
pelangi girls naget
pelangi girls naget
2rb+ terjual
4.9
Seblak RAFAEL | Seblak MAMANG RAFAEL | Seblak Viral
Rp40.000
Naturally Plus Jakarta
Naturally Plus Jakarta
100+ terjual
5.0

In [113]:
# Simpan hasil scraping ke dalam pandas DataFrame
df = pd.DataFrame(data)

# DATA PREPARATION

### Data Exploration

In [114]:
# Menampilkan 10 baris pertama DataFrame
df.head(10)

,Nama Produk,Harga Produk,Nama Toko,Kota Toko,Banyaknya Terjual,Rating Produk
0,Gelifood Seblak Instan Kerupuk Mawar Bumbu Ken...,Rp13.000,Lidigeli,Kab. Garut,250+ terjual,4.9
1,Seblak Instan Ceu Nthien Khas Bandung Rasana N...,Rp15.000,Central Seblak Nusantara,Tangerang Selatan,2rb+ terjual,4.9
2,"Seblak Rafael, Seblak Coet Instan Halal",Rp25.000,Brother Meat Shop,Depok,50+ terjual,5.0
3,Seblak Instan,Rp8.000,ROEMAH MOSLEM,Kab. Boyolali,19 terjual,5.0
4,KRUPUK STIK RASA UDANG CAP PADI KAPAS KHAS IND...,Rp19.050,dariimyu,Kab. Indramayu,100+ terjual,5.0
5,Seblak Instan Pedas Home Made,Rp3.500,the Dhecip,Tangerang Selatan,2rb+ terjual,4.8
6,Kylafood Seblak Cup,Rp11.000,Kylafood Jakarta,Jakarta Selatan,100+ terjual,4.9
7,seblak frozen,Rp10.400,pelangi girls naget,Jakarta Timur,2rb+ terjual,4.9
8,Seblak RAFAEL | Seblak MAMANG RAFAEL | Seblak ...,Rp40.000,Naturally Plus Jakarta,Kab. Tangerang,100+ terjual,5.0
9,Gelifood Seblak Instan Kerupuk Mawar Bumbu Ken...,Rp13.000,Lidigeli,Kab. Garut,250+ terjual,4.9

In [115]:
# Menampilkan informasi seluruh DataFrame yang ada
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Nama Produk        90 non-null     object
 1   Harga Produk       90 non-null     object
 2   Nama Toko          90 non-null     object
 3   Kota Toko          90 non-null     object
 4   Banyaknya Terjual  90 non-null     object
 5   Rating Produk      90 non-null     object
dtypes: object(6)
memory usage: 4.3+ KB

Dari data di atas terlihat bahwa jumlah kolom ada 6
Langkah selanjutnya adalah:
1. Memastikan apakah benar-benar tidak ada missing value (data null)?
2. Memastikan data unik dari setiap data
3. Membuat data sesuai datatypenya

In [116]:
# Cek missing alue
cek_miss = df.isnull().sum()
print(f'double check missing value:\n{cek_miss}')

double check missing value:
Nama Produk          0
Harga Produk         0
Nama Toko            0
Kota Toko            0
Banyaknya Terjual    0
Rating Produk        0
dtype: int64

Insight: Tidak ada data nul

In [117]:
# Menampilkan data unik dari dataframe
print(f"Berikut adalah jumlah data unik dari setiap kolom:\n{df.nunique()}\n")

data_unik_nama = df['Nama Produk'].unique()
data_unik_penjual = df['Nama Toko'].unique()
data_unik_toko = df['Kota Toko'].unique()

print(f"Nama Produk yang muncul pada data adalah:\n {data_unik_nama}\n")
print(f"Nama Toko yang ada pada data adalah:\n {data_unik_penjual}\n")
print(f"Kota Toko antara lain:\n {data_unik_toko}")

Berikut adalah jumlah data unik dari setiap kolom:
Nama Produk          9
Harga Produk         9
Nama Toko            9
Kota Toko            8
Banyaknya Terjual    5
Rating Produk        3
dtype: int64

Nama Produk yang muncul pada data adalah:
 ['Gelifood Seblak Instan Kerupuk Mawar Bumbu Kencur Rafael Pedas Gurih'
 'Seblak Instan Ceu Nthien Khas Bandung Rasana Ngeunah Pisan'
 'Seblak Rafael, Seblak Coet Instan Halal' 'Seblak Instan'
 'KRUPUK STIK RASA UDANG CAP PADI KAPAS KHAS INDRAMAYU BISA BUAT SEBLAK'
 'Seblak Instan Pedas Home Made' 'Kylafood Seblak Cup' 'seblak frozen'
 'Seblak RAFAEL | Seblak MAMANG RAFAEL | Seblak Viral']

Nama Toko yang ada pada data adalah:
 ['Lidigeli' 'Central Seblak Nusantara' 'Brother Meat Shop' 'ROEMAH MOSLEM'
 'dariimyu' 'the Dhecip' 'Kylafood Jakarta' 'pelangi girls naget'
 'Naturally Plus Jakarta']

Kota Toko antara lain:
 ['Kab. Garut' 'Tangerang Selatan' 'Depok' 'Kab. Boyolali' 'Kab. Indramayu'
 'Jakarta Selatan' 'Jakarta Timur' 'Kab. Tangerang']

### Data Cleaning

In [118]:
# Menghapus karakter non angka suapay bisa menjadi type INT
df['Harga Produk'] = df['Harga Produk'].str.replace('Rp', '')
df['Harga Produk'] = df['Harga Produk'].str.replace('.', '')

In [119]:
# Merubah type data menjadi INT
df['Harga Produk'] = df['Harga Produk'].astype(int)

In [120]:
# Menghapus karakter non angka suapay bisa menjadi type INT dan merubah rb menjadi '000'
df['Banyaknya Terjual'] = df['Banyaknya Terjual'].str.replace('+ terjual', '')
df['Banyaknya Terjual'] = df['Banyaknya Terjual'].str.replace('rb', '000')
df['Banyaknya Terjual'] = df['Banyaknya Terjual'].str.replace(' terjual', '')

In [125]:
# Merubah type data menjadi INT
df['Banyaknya Terjual'] = df['Banyaknya Terjual'].astype(int)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Nama Produk        90 non-null     object
 1   Harga Produk       90 non-null     int64
 2   Nama Toko          90 non-null     object
 3   Kota Toko          90 non-null     object
 4   Banyaknya Terjual  90 non-null     int64
 5   Rating Produk      90 non-null     object
dtypes: int64(2), object(4)
memory usage: 4.3+ KB

In [126]:
# Merubah type data menjadi Float
df['Rating Produk'] = df['Rating Produk'].astype(float)

In [128]:
df.head(10)
# Sekarang tampilannya seperti ini:

,Nama Produk,Harga Produk,Nama Toko,Kota Toko,Banyaknya Terjual,Rating Produk
0,Gelifood Seblak Instan Kerupuk Mawar Bumbu Ken...,13000,Lidigeli,Kab. Garut,250,4.9
1,Seblak Instan Ceu Nthien Khas Bandung Rasana N...,15000,Central Seblak Nusantara,Tangerang Selatan,2000,4.9
2,"Seblak Rafael, Seblak Coet Instan Halal",25000,Brother Meat Shop,Depok,50,5.0
3,Seblak Instan,8000,ROEMAH MOSLEM,Kab. Boyolali,19,5.0
4,KRUPUK STIK RASA UDANG CAP PADI KAPAS KHAS IND...,19050,dariimyu,Kab. Indramayu,100,5.0
5,Seblak Instan Pedas Home Made,3500,the Dhecip,Tangerang Selatan,2000,4.8
6,Kylafood Seblak Cup,11000,Kylafood Jakarta,Jakarta Selatan,100,4.9
7,seblak frozen,10400,pelangi girls naget,Jakarta Timur,2000,4.9
8,Seblak RAFAEL | Seblak MAMANG RAFAEL | Seblak ...,40000,Naturally Plus Jakarta,Kab. Tangerang,100,5.0
9,Gelifood Seblak Instan Kerupuk Mawar Bumbu Ken...,13000,Lidigeli,Kab. Garut,250,4.9

In [129]:
df.info()
# Sekarang datatypenya seperti ini:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Nama Produk        90 non-null     object
 1   Harga Produk       90 non-null     int64
 2   Nama Toko          90 non-null     object
 3   Kota Toko          90 non-null     object
 4   Banyaknya Terjual  90 non-null     int64
 5   Rating Produk      90 non-null     float64
dtypes: float64(1), int64(2), object(3)
memory usage: 4.3+ KB

# DATA ANALYSIS

### Mean, median, standar deviasi, skewness, dan kurtosis

In [130]:
# Saya ingin menampilkan dataframe baru bernama df_deskriptif dimana kolomnya terdiri dari hari, qty dan rating
# Sedamgkan untuk barisnya adalah perhitungan yang saya butuhkan

# Jadi pertama buat variabel sementara yang hanya memanggil data bertype selain object
df_angka = df[df.columns[df.dtypes != 'object']]
# hitung central tendency dari tabel utama
rt = df_angka.mean()
sd = df_angka.std() 
sk = df_angka.skew() 
ku = df_angka.kurtosis() 
min = df_angka.min()
q1 = df_angka.quantile(0.25) 
at = df_angka.median() 
q3 = df_angka.quantile(0.75) 
max = df_angka.max()

# tabel barunya
df_deskriptif = pd.DataFrame({
    'rata_rata' : rt,
    'standar_deviasi' : sd,
    'skewness' : sk,
    'kurtosis' : ku,
    'terendah' : min,
    '25%' : q1,
    'angka_tengah' : at,
    '75%' : q3,
    'tertinggi' : max   
})

# tabel baru ditranspose supaya kolom swap dengan row seupaya lebih mudah dalam membaca
df_deskriptif['rata_rata'] = df_deskriptif['rata_rata'].round(2)
df_deskriptif['standar_deviasi'] = df_deskriptif['standar_deviasi'].round(2)
df_deskriptif['skewness'] = df_deskriptif['skewness'].round(2)
df_deskriptif['kurtosis'] = df_deskriptif['kurtosis'].round(2)
df_deskriptif['terendah'] = df_deskriptif['terendah'].round(2)
df_deskriptif['25%'] = df_deskriptif['25%'].round(2)
df_deskriptif['angka_tengah'] = df_deskriptif['angka_tengah'].round(2)
df_deskriptif['75%'] = df_deskriptif['75%'].round(2)
df_deskriptif['tertinggi'] = df_deskriptif['tertinggi'].round(2)

df_deskriptif

,rata_rata,standar_deviasi,skewness,kurtosis,terendah,25%,angka_tengah,75%,tertinggi
Harga Produk,16105.56,10346.86,1.19,0.71,3500.0,10400.0,13000.0,19050.0,40000.0
Banyaknya Terjual,735.44,901.15,0.71,-1.52,19.0,100.0,100.0,2000.0,2000.0
Rating Produk,4.93,0.07,-0.51,-0.72,4.8,4.9,4.9,5.0,5.0

### Potensi Pendapatan Tambahan

In [131]:
# Saya definisikan terlebih dahulu Standard deviasi dan jumlah populasi 
hp_std = df['Harga Produk'].std()
N = len(df)

'''
Dari sini baru bisa saya hitung potensi Pendapatan per Produk dengan
harga Minimum dan harga Maksimum
level confidence = 95%
'''

low_hp, up_hp = stats.norm.interval(0.95,loc=df['Harga Produk'].mean(),scale=hp_std/np.sqrt(N))
print('Potensi Minimum Pendapatan per Produk:',low_hp.round(2))
print('Potensi Maksimum Pendapatan per Produk:',up_hp.round(2))

Potensi Minimum Pendapatan per Produk: 13967.91
Potensi Maksimum Pendapatan per Produk: 18243.2

In [132]:
# Saya definisikan terlebih dahulu Standard deviasi dan jumlah populasi 
s_std = df['Banyaknya Terjual'].std()
N = len(df)

'''
Dari sini baru bisa saya hitung potensi Penjualan Produk per Bulan dengan
penjualan Minimum dan Maksimum
level confidence = 95%
'''

low_s, up_s = stats.norm.interval(0.95,loc=df['Banyaknya Terjual'].mean(),scale=s_std/np.sqrt(N))
print('Potensi Minimum Produk Terjual per Bulan:',low_s.round(2))
print('Potensi Maksimum Produk Terjual per Bulan:',up_s.round(2))

Potensi Minimum Produk Terjual per Bulan: 549.27
Potensi Maksimum Produk Terjual per Bulan: 921.62

In [133]:
'''
Saya sudah mendapatkan perhitungan ini:
Potensi Minimum Pendapatan per Produk
Potensi Maksimum Pendapatan per Produk
Potensi Minimum Produk Terjual per Bulan
Potensi Maksimum Produk Terjual per Bulan

Sekarang saatnya mengalikan antara pendapatan per produk dengan penjualan per bulan
'''

min_income = low_hp * low_s
max_income = up_hp * up_s

min_income = min_income.round(2)
max_income = max_income.round(2)

print('Potensi Minimum Pendapatan Tambahan Saya Setiap Bulan:', min_income)
print('Potensi Maksimum Pendapatan Tambahan Saya Setiap Bulan:', max_income)

Potensi Minimum Pendapatan Tambahan Saya Setiap Bulan: 7672127.88
Potensi Maksimum Pendapatan Tambahan Saya Setiap Bulan: 16813312.55

### APAKAH TARGET SAYA AKAN TERCAPAI?

In [134]:
# Potensi pendapatan selama 6 bulan (Saya ambil potensi minimum)
target = 30000000
bulan = 6

print(f'potensi income tambahan:\n{min_income*bulan}\n')

if target <= min_income * bulan:
    print('target akan tercapai')
else:
    print('atur ulang strategi atau target!')

potensi income tambahan:
46032767.28

target akan tercapai

### Perbandingan harga Jabodetabek dan Luar Jabodetabek

Saya harus mengelompokkan terlebih dahulu, kota-kota yang masuk wilayah JABODETABEK
dan luar JABODETABEK

In [136]:
# Sebelumnya saya perlu melihat lagi kota apa saja yang ada di dalam data
list_kota = df['Kota Toko'].unique()
print('kota yang ada di dalm data adalah sebagai berikut:\n',list_kota)

kota yang ada di dalm data adalah sebagai berikut:
 ['Kab. Garut' 'Tangerang Selatan' 'Depok' 'Kab. Boyolali' 'Kab. Indramayu'
 'Jakarta Selatan' 'Jakarta Timur' 'Kab. Tangerang']

In [137]:
# Ok, saya akan mendefinisikan kota mana yang termasuk JABODETABEK
JaBoDeTaBek = ['Jakarta', 'Bogor', 'Depok', 'Tangerang', 'Bekasi']

# Semua kota yang terdapat kata yang ada di JABODETABEK, akan termasuk True. Dan sebaliknya
df['Kawasan'] = df['Kota Toko'].str.contains('|'.join(JaBoDeTaBek), case=False)
df

,Nama Produk,Harga Produk,Nama Toko,Kota Toko,Banyaknya Terjual,Rating Produk,Kawasan
0,Gelifood Seblak Instan Kerupuk Mawar Bumbu Ken...,13000,Lidigeli,Kab. Garut,250,4.9,False
1,Seblak Instan Ceu Nthien Khas Bandung Rasana N...,15000,Central Seblak Nusantara,Tangerang Selatan,2000,4.9,True
2,"Seblak Rafael, Seblak Coet Instan Halal",25000,Brother Meat Shop,Depok,50,5.0,True
3,Seblak Instan,8000,ROEMAH MOSLEM,Kab. Boyolali,19,5.0,False
4,KRUPUK STIK RASA UDANG CAP PADI KAPAS KHAS IND...,19050,dariimyu,Kab. Indramayu,100,5.0,False
...,...,...,...,...,...,...,...
85,KRUPUK STIK RASA UDANG CAP PADI KAPAS KHAS IND...,19050,dariimyu,Kab. Indramayu,100,5.0,False
86,Seblak Instan Pedas Home Made,3500,the Dhecip,Tangerang Selatan,2000,4.8,True
87,Kylafood Seblak Cup,11000,Kylafood Jakarta,Jakarta Selatan,100,4.9,True
88,seblak frozen,10400,pelangi girls naget,Jakarta Timur,2000,4.9,True
89,Seblak RAFAEL | Seblak MAMANG RAFAEL | Seblak ...,40000,Naturally Plus Jakarta,Kab. Tangerang,100,5.0,True

In [138]:
# Terakhir, saya akan ubah nilai True debgab JABODETABEK, dan False Luar JABODETABEK
df['Kawasan'] = df['Kawasan'].map({True: 'JABODETABEK', False: 'Luar JABODETABEK'})
df

,Nama Produk,Harga Produk,Nama Toko,Kota Toko,Banyaknya Terjual,Rating Produk,Kawasan
0,Gelifood Seblak Instan Kerupuk Mawar Bumbu Ken...,13000,Lidigeli,Kab. Garut,250,4.9,Luar JABODETABEK
1,Seblak Instan Ceu Nthien Khas Bandung Rasana N...,15000,Central Seblak Nusantara,Tangerang Selatan,2000,4.9,JABODETABEK
2,"Seblak Rafael, Seblak Coet Instan Halal",25000,Brother Meat Shop,Depok,50,5.0,JABODETABEK
3,Seblak Instan,8000,ROEMAH MOSLEM,Kab. Boyolali,19,5.0,Luar JABODETABEK
4,KRUPUK STIK RASA UDANG CAP PADI KAPAS KHAS IND...,19050,dariimyu,Kab. Indramayu,100,5.0,Luar JABODETABEK
...,...,...,...,...,...,...,...
85,KRUPUK STIK RASA UDANG CAP PADI KAPAS KHAS IND...,19050,dariimyu,Kab. Indramayu,100,5.0,Luar JABODETABEK
86,Seblak Instan Pedas Home Made,3500,the Dhecip,Tangerang Selatan,2000,4.8,JABODETABEK
87,Kylafood Seblak Cup,11000,Kylafood Jakarta,Jakarta Selatan,100,4.9,JABODETABEK
88,seblak frozen,10400,pelangi girls naget,Jakarta Timur,2000,4.9,JABODETABEK
89,Seblak RAFAEL | Seblak MAMANG RAFAEL | Seblak ...,40000,Naturally Plus Jakarta,Kab. Tangerang,100,5.0,JABODETABEK

In [139]:
# Dari sini, pertama saya harus menghitung rata-ratanya
# Menghitung rata-rata harga di kawasan JABODETABEK
avg_jabodetabek = df[df['Kawasan'] == 'JABODETABEK']['Harga Produk'].mean()
avg_jabodetabek = avg_jabodetabek.round()
print('Rata-rata harga per produk di kawasan JABODETABEK adalah: ', avg_jabodetabek)

# Menghitung rata-rata harga di luar kawasan JABODETABEK
avg_luar_jabodetabek = df[df['Kawasan'] == 'Luar JABODETABEK']['Harga Produk'].mean()
avg_luar_jabodetabek = avg_luar_jabodetabek.round()
print('Rata-rata harga per produk di luar kawasan JABODETABEK adalah: ', avg_luar_jabodetabek)

Rata-rata harga per produk di kawasan JABODETABEK adalah:  17483.0
Rata-rata harga per produk di luar kawasan JABODETABEK adalah:  13350.0

Rata-rata harga produk di kawasan JABODETABEK sekitar 1.6 x lebih tinggi daripada rata-rata harga produk di luar kawasan JABODETABEK

H0: Rata-rata harga produk di kawasan JABODETABEK == Luar JABODETABEK
H1: Rata-rata harga produk di kawasan JABODETABEK =! Luar JABODETABEK

In [140]:
hp_JABODETABEK = df[df['Kawasan'] == 'JABODETABEK']['Harga Produk']
hp_luar_JABODETABEK = df[df['Kawasan'] == 'Luar JABODETABEK']['Harga Produk']

t_stat, p_val = stats.ttest_ind (hp_JABODETABEK , hp_luar_JABODETABEK)
print('T-Statistic:',t_stat)
print('P-value:',p_val)

T-Statistic: 1.8091863420996195
P-value: 0.07383671055490759

Seperti kita ketahui, semakin besar nilai t-statistic maka semakin besar pula perbedaan antar variabel. Dieperkuat lagi dengan nilai P yang standardnya adalah 0.05, nilai P di sini di bawah nilai tersebut. Artinya, dalam uji statistik ini H0 tidak dapat diterima.

Dengan kata lain, Rata-rata harga produk di JABODETABEK TIDAK SAMA dengan luar Jabodetabek

Dari data rata-rata harga ini saya akan memilih supplier dari Luar JABODETABEK

### Apakah orang lebih cenderung suka dengan produk yang harganya murah?

In [141]:
# Definisikan produk mahal vs murah berdasarkan rata-ratanya
# Jika harga di bawah rata-rata harga, maka murah. Dan sebaliknya

# Ok, saya akan mendefinisikan kota mana yang termasuk JABODETABEK
Kelas_Harga = ['Mahal', 'Murah']

# Semua kota yang terdapat kata yang ada di JABODETABEK, akan termasuk True. Dan sebaliknya
harga_rata_rata= df['Harga Produk'].mean()

df['Kelas Harga'] = df['Harga Produk'].apply(lambda x: 'Murah' if x < harga_rata_rata else 'Mahal')

df

,Nama Produk,Harga Produk,Nama Toko,Kota Toko,Banyaknya Terjual,Rating Produk,Kawasan,Kelas Harga
0,Gelifood Seblak Instan Kerupuk Mawar Bumbu Ken...,13000,Lidigeli,Kab. Garut,250,4.9,Luar JABODETABEK,Murah
1,Seblak Instan Ceu Nthien Khas Bandung Rasana N...,15000,Central Seblak Nusantara,Tangerang Selatan,2000,4.9,JABODETABEK,Murah
2,"Seblak Rafael, Seblak Coet Instan Halal",25000,Brother Meat Shop,Depok,50,5.0,JABODETABEK,Mahal
3,Seblak Instan,8000,ROEMAH MOSLEM,Kab. Boyolali,19,5.0,Luar JABODETABEK,Murah
4,KRUPUK STIK RASA UDANG CAP PADI KAPAS KHAS IND...,19050,dariimyu,Kab. Indramayu,100,5.0,Luar JABODETABEK,Mahal
...,...,...,...,...,...,...,...,...
85,KRUPUK STIK RASA UDANG CAP PADI KAPAS KHAS IND...,19050,dariimyu,Kab. Indramayu,100,5.0,Luar JABODETABEK,Mahal
86,Seblak Instan Pedas Home Made,3500,the Dhecip,Tangerang Selatan,2000,4.8,JABODETABEK,Murah
87,Kylafood Seblak Cup,11000,Kylafood Jakarta,Jakarta Selatan,100,4.9,JABODETABEK,Murah
88,seblak frozen,10400,pelangi girls naget,Jakarta Timur,2000,4.9,JABODETABEK,Murah
89,Seblak RAFAEL | Seblak MAMANG RAFAEL | Seblak ...,40000,Naturally Plus Jakarta,Kab. Tangerang,100,5.0,JABODETABEK,Mahal

In [142]:
# Sekarang kita hitung jumlah penjualan kategori Murah dan Kategori Mahal

terjual_kelas_mahal = df[df['Kelas Harga'] == 'Mahal']['Banyaknya Terjual'].sum()
print('Produk yang terjual dari kelas harga di atas rata-rata adalah:\n' , terjual_kelas_mahal , 'kali')

terjual_kelas_murah = df[df['Kelas Harga'] == 'Murah']['Banyaknya Terjual'].sum()
print('Produk yang terjual dari kelas harga di bawah rata-rata adalah:\n' , terjual_kelas_murah , 'kali')

Produk yang terjual dari kelas harga di atas rata-rata adalah:
 2500 kali
Produk yang terjual dari kelas harga di bawah rata-rata adalah:
 63690 kali

Uji Hipotesa

Kali ini saya akan menggunakan The Mann-Whitney U test 
The Mann-Whitney U test is a nonparametric test (data are not normally distributed). In other words, we use a Mann-Whitney test to determine whether there is a difference in a continuous variable between two independent groups (categorical variable). For example, we want to compare whether there is a difference in IQ score (continuous variable) between male and female students (categorical variable).

reference : https://shorturl.at/uvJY5 | https://shorturl.at/HKR12

H0 : Tidak ada perbedaan signifikan atara kelas harga dengan jumlah produk terjual
H1 : Terdapat perbedaan signifikan atara kelas harga dengan jumlah produk terjual

In [143]:
from scipy.stats import mannwhitneyu

uji_murah = df[df['Kelas Harga'] == 'Murah']['Banyaknya Terjual']
uji_mahal = df[df['Kelas Harga'] == 'Murah']['Banyaknya Terjual']

statistic, p_value = mannwhitneyu(uji_murah, uji_mahal)

print('Nilai U: ', statistic)
print('P-value :', p_value)

alpha = 0.05

if p_value < alpha:
    print('TOLAK H0')
else:
    print('TERIMA H0')

Nilai U:  1800.0
P-value : 1.0
TERIMA H0

Statistik menunjukkan hasil tolak H0
Artinya H1 : Terdapat perbedaan signifikan atara kelas harga dengan jumlah produk terjual
Dapat diterima

# CONCLUSION

**Objective:**

Mendapatkan penghasilan tambahan sebesar 30juta dengan menjadi dropshiper dalam waktu 6 bulan

**Berdasarkan proses analisis yang saya lakukan, project ini dapat dijalankan dan key result dapat dipenuhi**

**Key Result:**

1. Mengumpulkan 50 - 100 data penjualan di Tokopedia

**Saya mendapatkan data sebanyak 90 produk tidak termasuk produk yang dikiiklankan dengan hanya memanggil css
dari produk reguler saja**

2. Tidak memperhitungkan data dari produk yang diiklankan

**Point ini sudah terpenuhi**

3. Menghitung potensi pemasukan, jika lebih atau sama dengan kebutuhan saya, maka
project ini dilanjutkan

**Potensi pemasukan tambahan saya dalam 6 bulan ke depan adalah sebesar 38.687.060,88 itu artinya project ini bisa untuk dijalankan**

4. Mencari insight daerah mana yang menjual produk lebih murah

**JABODETABEK ternyata memiliki harga lebih tinggi dibandingkan luar JABODETABEK**

5. Mencari tahu apakah semakin murah harga, semakin banyak pembeli?

**Ya, semakin murah harga, pembeli semakin banyak**

In [146]:
df.to_csv('Ahmad-Qais-Scraping.csv')