# INTRODUCION

- Nama : Ahmad Qais
- Batch : RMT 026
- Objective :

Live Code 2 ini dibuat guna mengevaluasi SQL dan Pandas sebagai berikut:

Mampu melakukan analisa data di SQL.
Mampu melakukan pengambilan data dari SQL.
Mampu melakukan pengolahan data di pandas.
Mampu menerapkan looping, conditional, serta query agggregation menggunakan pandas.

In [16]:
from google.colab import auth
from google.cloud import bigquery
auth.authenticate_user()
print('Authenticated')

project_id_akun = "river-nation-405906" #GUNAKAN GCP PROJECT-ID KALIAN MASING-MASING
client = bigquery.Client(project='river-nation-405906')

Authenticated

# ANSWER

## PROBLEM 1

1. Code di bawah menunjukkan nama-nama perusahaan yang ada:

In [65]:
df = client.query('''
SELECT *
FROM `ftds-hacktiv8-project.phase0_ftds_026_rmt.taxi_fare`
''').to_dataframe()

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9286 entries, 0 to 9285
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   unique_key            9286 non-null   object
 1   taxi_id               9286 non-null   object
 2   trip_start_timestamp  9286 non-null   datetime64[ns, UTC]
 3   trip_end_timestamp    9286 non-null   datetime64[ns, UTC]
 4   trip_km               9286 non-null   float64
 5   fare                  9286 non-null   float64
 6   tips                  9286 non-null   float64
 7   payment_type          9286 non-null   object
 8   company               9286 non-null   object
 9   pickup_location       9286 non-null   object
 10  dropoff_location      9286 non-null   object
dtypes: datetime64[ns, UTC](2), float64(3), object(6)
memory usage: 798.1+ KB

In [ ]:
df = client.query('''
SELECT DISTINCT company
FROM `ftds-hacktiv8-project.phase0_ftds_026_rmt.taxi_fare`
''').to_dataframe()

df

KNOWLEDGE:

Diketahui terdapat 5 perusahaan, dengan nama tertera di atas

2. Code di bawah menunjukkan nilai min dan max waktu pengambilan data:

In [ ]:
df = client.query('''
SELECT MIN(trip_start_timestamp), MAX(trip_start_timestamp)
FROM `ftds-hacktiv8-project.phase0_ftds_026_rmt.taxi_fare`
''').to_dataframe()

df

Waktu Min adalah = 2021-01-02 11:00:00+00:00

Waktu Max adalah = 2022-12-31 14:15:00+00:00

In [ ]:
# Pembuktian, nilai min dengan menggunakan code sorting by date:
df = client.query('''
SELECT *
FROM `ftds-hacktiv8-project.phase0_ftds_026_rmt.taxi_fare`
ORDER BY trip_start_timestamp
''').to_dataframe()

df

In [ ]:
# # Pembuktian, nilai max dengan menggunakan code sorting DESC by date:

df = client.query('''
SELECT *
FROM `ftds-hacktiv8-project.phase0_ftds_026_rmt.taxi_fare`
ORDER BY trip_start_timestamp DESC;
''').to_dataframe()

df

3.
Code di bawah untuk membandingkan banyaknya perjalanan seluruh perusahaan tahun 2022

In [70]:
df = client.query('''
SELECT trip_start_timestamp,
  EXTRACT(year FROM trip_start_timestamp) AS year
FROM `ftds-hacktiv8-project.phase0_ftds_026_rmt.taxi_fare`
''').to_dataframe()

df

          trip_start_timestamp  year
0    2021-05-18 19:30:00+00:00  2021
1    2021-05-30 15:15:00+00:00  2021
2    2021-06-05 19:30:00+00:00  2021
3    2021-06-13 13:45:00+00:00  2021
4    2021-07-07 15:15:00+00:00  2021
...                        ...   ...
9281 2021-04-06 16:00:00+00:00  2021
9282 2022-11-13 15:30:00+00:00  2022
9283 2021-05-14 15:30:00+00:00  2021
9284 2021-04-30 18:00:00+00:00  2021
9285 2022-07-12 14:45:00+00:00  2022

[9286 rows x 2 columns]

In [76]:
df = client.query('''
SELECT company, count(*) AS total_trip_company
FROM `ftds-hacktiv8-project.phase0_ftds_026_rmt.taxi_fare`
WHERE YEAR(trip_start_timestamp) = 2022
GROUP BY company;
''').to_dataframe()

df

BadRequest: ignored

4. Kode di bawah untuk menunjukkan perusahaan dengan tarif perjalanan per KM termurah:

In [67]:
# Kode ini untuk mencari perusahaan apa yang memiliki fare terendah. Dengan menggunakan group by company dan memilih perusahaan teratas (terendah)

df = client.query('''
SELECT company, MIN(fare) AS cheapest
FROM `ftds-hacktiv8-project.phase0_ftds_026_rmt.taxi_fare`
GROUP BY company
ORDER BY cheapest
LIMIT 1;
''').to_dataframe()

df

         company  cheapest
0  Synctaxi Inc.       0.0

Synctaxi Inc.	adalah perusahaan dengan fare terendah

## PROBLEM 2

In [52]:
# SETUP
import pandas as pd

In [57]:
df = client.query('''
SELECT *
FROM `ftds-hacktiv8-project.phase0_ftds_026_rmt.taxi_fare`
''').to_dataframe()

df.head(8)

,unique_key,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_km,fare,tips,payment_type,company,pickup_location,dropoff_location
0,DP-250,D-7,2021-05-18 19:30:00+00:00,2021-05-18 19:45:00+00:00,3.057746,9.00,0.0,Cash,Deluc Porter,POINT (-87.6333080367 41.899602111),POINT (-87.6635175498 41.874005383)
1,DP-289,D-7,2021-05-30 15:15:00+00:00,2021-05-30 15:45:00+00:00,21.082354,35.50,0.0,Cash,Deluc Porter,POINT (-87.913624596 41.9802643146),POINT (-87.6950125892 42.001571027)
2,DP-316,D-7,2021-06-05 19:30:00+00:00,2021-06-05 19:45:00+00:00,7.242030,14.00,0.0,Cash,Deluc Porter,POINT (-87.913624596 41.9802643146),POINT (-87.8045320063 41.9850151008)
3,DP-354,D-7,2021-06-13 13:45:00+00:00,2021-06-13 14:15:00+00:00,22.369826,37.25,0.0,Credit Card,Deluc Porter,POINT (-87.913624596 41.9802643146),POINT (-87.6559981815 41.9442266014)
4,DP-501,D-7,2021-07-07 15:15:00+00:00,2021-07-07 15:30:00+00:00,3.218680,9.00,0.0,Cash,Deluc Porter,POINT (-87.6333080367 41.899602111),POINT (-87.6635175498 41.874005383)
5,DP-794,D-7,2021-08-25 13:45:00+00:00,2021-08-25 14:15:00+00:00,21.565156,35.75,0.0,Cash,Deluc Porter,POINT (-87.913624596 41.9802643146),POINT (-87.6950125892 42.001571027)
6,DP-926,D-7,2021-09-21 20:30:00+00:00,2021-09-21 20:30:00+00:00,0.500000,3.25,0.0,Cash,Deluc Porter,POINT (-87.9030396611 41.9790708201),POINT (-87.9030396611 41.9790708201)
7,DP-1470,D-7,2022-04-18 20:30:00+00:00,2022-04-18 20:30:00+00:00,0.500000,3.25,0.0,Cash,Deluc Porter,POINT (-87.6558787862 41.96581197),POINT (-87.6558787862 41.96581197)

In [ ]:
def keterangan_waktu